USE `u192092963_yemeraindia`;

-- Yeh Mera India safe schema sync
-- Non-destructive: no DROP, TRUNCATE, DELETE or table recreation.

CREATE TABLE IF NOT EXISTS books (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  author_id BIGINT UNSIGNED NULL,
  title VARCHAR(220) NOT NULL,
  description LONGTEXT NOT NULL,
  purchase_url VARCHAR(2000) NOT NULL,
  cover_image LONGTEXT NULL,
  image_prompt TEXT NULL,
  keywords TEXT NULL,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  published_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE books ADD COLUMN IF NOT EXISTS author_id BIGINT UNSIGNED NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS title VARCHAR(220) NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN IF NOT EXISTS description LONGTEXT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS purchase_url VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN IF NOT EXISTS cover_image LONGTEXT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS image_prompt TEXT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS keywords TEXT NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS status ENUM('draft','published') NOT NULL DEFAULT 'draft';
ALTER TABLE books ADD COLUMN IF NOT EXISTS published_at DATETIME NULL;
ALTER TABLE books ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE books ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS play_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  author_id BIGINT UNSIGNED NULL,
  play_title VARCHAR(220) NOT NULL,
  event_title VARCHAR(220) NOT NULL,
  description LONGTEXT NOT NULL,
  venue VARCHAR(300) NOT NULL,
  event_at DATETIME NULL,
  ticket_url VARCHAR(2000) NULL,
  keywords TEXT NULL,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  published_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE play_events ADD COLUMN IF NOT EXISTS author_id BIGINT UNSIGNED NULL;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS play_title VARCHAR(220) NOT NULL DEFAULT '';
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS event_title VARCHAR(220) NOT NULL DEFAULT '';
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS description LONGTEXT NULL;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS venue VARCHAR(300) NOT NULL DEFAULT '';
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS event_at DATETIME NULL;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS ticket_url VARCHAR(2000) NULL;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS keywords TEXT NULL;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS status ENUM('draft','published') NOT NULL DEFAULT 'draft';
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS published_at DATETIME NULL;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE play_events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS social_videos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  author_id BIGINT UNSIGNED NULL,
  title VARCHAR(220) NOT NULL,
  description LONGTEXT NOT NULL,
  video_url VARCHAR(2000) NOT NULL,
  platform ENUM('youtube','instagram') NOT NULL DEFAULT 'youtube',
  keywords TEXT NULL,
  related_type ENUM('none','book','play','post') NOT NULL DEFAULT 'none',
  related_id BIGINT UNSIGNED NULL,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  published_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS author_id BIGINT UNSIGNED NULL;
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS title VARCHAR(220) NOT NULL DEFAULT '';
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS description LONGTEXT NULL;
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS video_url VARCHAR(2000) NOT NULL DEFAULT '';
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS platform ENUM('youtube','instagram') NOT NULL DEFAULT 'youtube';
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS keywords TEXT NULL;
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS related_type ENUM('none','book','play','post') NOT NULL DEFAULT 'none';
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS related_id BIGINT UNSIGNED NULL;
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS status ENUM('draft','published') NOT NULL DEFAULT 'draft';
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS published_at DATETIME NULL;
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE social_videos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Preserve and align existing post records. No rows are changed here.
ALTER TABLE posts ADD COLUMN IF NOT EXISTS author_id BIGINT UNSIGNED NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS excerpt TEXT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS cover_image LONGTEXT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_alt VARCHAR(255) NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS keywords TEXT NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS category VARCHAR(100) NOT NULL DEFAULT 'Journal';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS status ENUM('draft','published') NOT NULL DEFAULT 'draft';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS featured TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS published_at DATETIME NULL;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Verification only. These statements do not change data.
SELECT DATABASE() AS selected_database;
SELECT 'posts' AS table_name, COUNT(*) AS total_rows FROM posts
UNION ALL SELECT 'books', COUNT(*) FROM books
UNION ALL SELECT 'play_events', COUNT(*) FROM play_events
UNION ALL SELECT 'social_videos', COUNT(*) FROM social_videos
UNION ALL SELECT 'users', COUNT(*) FROM users
UNION ALL SELECT 'homepage_content', COUNT(*) FROM homepage_content
UNION ALL SELECT 'media_assets', COUNT(*) FROM media_assets
UNION ALL SELECT 'media_gallery', COUNT(*) FROM media_gallery
UNION ALL SELECT 'analytics_events', COUNT(*) FROM analytics_events
UNION ALL SELECT 'ai_jobs', COUNT(*) FROM ai_jobs
UNION ALL SELECT 'ai_settings', COUNT(*) FROM ai_settings;

SELECT id, title, slug, status, created_at, updated_at
FROM posts
ORDER BY id DESC;
